name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}
      NEXT_PUBLIC_ENABLE_TESTNETS: true
      NODE_ENV: ${{ secrets.NODE_ENV }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: install dependencies
        run: npm install
      - name: Build
        run: npm run build 
        env:
          CI: false
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: github-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.

permissions:
  contents: write
