name: Build and Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}
      NEXT_PUBLIC_ENABLE_TESTNETS: true
      NODE_ENV: ${{ secrets.NODE_ENV }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages # Name the artifact "github-pages"
          path: out # Path to the output directory containing the static files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write # Required for deployment to GitHub Pages
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages # Download the "github-pages" artifact uploaded in the build job

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          folder: out # Deploy the contents of the 'out' folder
